# Generated by Django 5.2.5 on 2025-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textupload',
            name='title',
            field=models.TextField(),
        ),
    ]
